### ISSUE TITLE
nginx-ingress-integrator fails in arm64 architecture

### ISSUE THREAD

**Issue by javierdelapuente** [canonical/nginx-ingress-integrator-operator#160]
### Bug Description

`nginx-ingress-integrator` does not work in arm64 architecture. This happens in stable and edge channels.

The error is: `ImportError: /var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/venv/cryptography/hazmat/bindings/_rust.abi3.so: cannot open shared object file: No such file or directory`

### To Reproduce

Deploy nginx-ingress-integrator in an existing model, with a constraint for arm64 architecture.
```
ubuntu@netbox:~$ juju deploy nginx-ingress-integrator --trust --constraints "arch=arm64"
```

### Environment

I am using MicroK8S 1.30-strict/stable and Juju 3.5.2.

It happens at least stable and edge channels for nginx-ingress-integrator

### Relevant log output

```shell
ubuntu@netbox:~$ juju debug-log --replay --include nginx-ingress-integrator
unit-nginx-ingress-integrator-0: 08:50:46 INFO juju.cmd running containerAgent [3.5.3 63d460f9ee6c7c710131961390687e7a0ab90470 gc go1.21.12]
unit-nginx-ingress-integrator-0: 08:50:46 INFO juju.cmd.containeragent.unit start "unit"
unit-nginx-ingress-integrator-0: 08:50:46 INFO juju.worker.upgradesteps upgrade steps for 3.5.3 have already been run.
unit-nginx-ingress-integrator-0: 08:50:46 INFO juju.worker.probehttpserver starting http server on 127.0.0.1:65301
unit-nginx-ingress-integrator-0: 08:50:46 INFO juju.api connection established to "wss://controller-service.controller-microk8s.svc.cluster.local:17070/model/6466ba98-1f87-4189-85ba-2f5ca72218a1/api"
unit-nginx-ingress-integrator-0: 08:50:46 INFO juju.worker.apicaller [6466ba] "unit-nginx-ingress-integrator-0" successfully connected to "controller-service.controller-microk8s.svc.cluster.local:17070"
unit-nginx-ingress-integrator-0: 08:50:46 INFO juju.api connection established to "wss://controller-service.controller-microk8s.svc.cluster.local:17070/model/6466ba98-1f87-4189-85ba-2f5ca72218a1/api"
unit-nginx-ingress-integrator-0: 08:50:46 INFO juju.worker.apicaller [6466ba] "unit-nginx-ingress-integrator-0" successfully connected to "controller-service.controller-microk8s.svc.cluster.local:17070"
unit-nginx-ingress-integrator-0: 08:50:46 INFO juju.worker.migrationminion migration migration phase is now: NONE
unit-nginx-ingress-integrator-0: 08:50:46 INFO juju.worker.logger logger worker started
unit-nginx-ingress-integrator-0: 08:50:46 WARNING juju.worker.proxyupdater unable to set snap core settings [proxy.http= proxy.https= proxy.store=]: exec: "snap": executable file not found in $PATH, output: ""
unit-nginx-ingress-integrator-0: 08:50:46 INFO juju.worker.caasupgrader abort check blocked until version event received
unit-nginx-ingress-integrator-0: 08:50:46 INFO juju.worker.caasupgrader unblocking abort check
unit-nginx-ingress-integrator-0: 08:50:46 INFO juju.worker.leadership nginx-ingress-integrator/0 promoted to leadership of nginx-ingress-integrator
unit-nginx-ingress-integrator-0: 08:50:46 INFO juju.agent.tools ensure jujuc symlinks in /var/lib/juju/tools/unit-nginx-ingress-integrator-0
unit-nginx-ingress-integrator-0: 08:50:46 INFO juju.worker.uniter unit "nginx-ingress-integrator/0" started
unit-nginx-ingress-integrator-0: 08:50:46 INFO juju.worker.uniter resuming charm install
unit-nginx-ingress-integrator-0: 08:50:46 INFO juju.worker.uniter.charm downloading ch:arm64/focal/nginx-ingress-integrator-111 from API server
unit-nginx-ingress-integrator-0: 08:50:46 INFO juju.downloader downloading from ch:arm64/focal/nginx-ingress-integrator-111
unit-nginx-ingress-integrator-0: 08:50:46 INFO juju.downloader download complete ("ch:arm64/focal/nginx-ingress-integrator-111")
unit-nginx-ingress-integrator-0: 08:50:47 INFO juju.downloader download verified ("ch:arm64/focal/nginx-ingress-integrator-111")
unit-nginx-ingress-integrator-0: 08:56:42 INFO juju.worker.uniter hooks are retried true
unit-nginx-ingress-integrator-0: 08:56:42 INFO juju.worker.uniter found queued "install" hook
unit-nginx-ingress-integrator-0: 08:56:45 WARNING unit.nginx-ingress-integrator/0.install Traceback (most recent call last):
unit-nginx-ingress-integrator-0: 08:56:45 WARNING unit.nginx-ingress-integrator/0.install   File "./src/charm.py", line 14, in <module>
unit-nginx-ingress-integrator-0: 08:56:45 WARNING unit.nginx-ingress-integrator/0.install     from charms.tls_certificates_interface.v3.tls_certificates import (
unit-nginx-ingress-integrator-0: 08:56:45 WARNING unit.nginx-ingress-integrator/0.install   File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/lib/charms/tls_certificates_interface/v3/tls_certificates.py", line 289, in <module>
unit-nginx-ingress-integrator-0: 08:56:45 WARNING unit.nginx-ingress-integrator/0.install     from cryptography import x509
unit-nginx-ingress-integrator-0: 08:56:45 WARNING unit.nginx-ingress-integrator/0.install   File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/venv/cryptography/x509/__init__.py", line 7, in <module>
unit-nginx-ingress-integrator-0: 08:56:45 WARNING unit.nginx-ingress-integrator/0.install     from cryptography.x509 import certificate_transparency, verification
unit-nginx-ingress-integrator-0: 08:56:45 WARNING unit.nginx-ingress-integrator/0.install   File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/venv/cryptography/x509/certificate_transparency.py", line 11, in <module>
unit-nginx-ingress-integrator-0: 08:56:45 WARNING unit.nginx-ingress-integrator/0.install     from cryptography.hazmat.bindings._rust import x509 as rust_x509
unit-nginx-ingress-integrator-0: 08:56:45 WARNING unit.nginx-ingress-integrator/0.install ImportError: /var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/venv/cryptography/hazmat/bindings/_rust.abi3.so: cannot open shared object file: No such file or directory
```

**Comment by cbartz** [comment]
@weiiwang01 Can you have a look if this is easily fixable, please?

**Comment by javierdelapuente** [comment]
arm64 is already working.
