### ISSUE TITLE
secret expiration fails due to key introduced in tls_certificate library upgrade

### ISSUE THREAD

**Issue by cbartz** [canonical/nginx-ingress-integrator-operator#162]
### Bug Description

We encounter a deployment with nginx-ingress-integrator (rev 108) in error state due to a failed `secret-expired` hook. The root cause is a missing key `csr` in the secret data:

```
unit-nginx-ingress-integrator-0: 11:13:27 DEBUG unit.nginx-ingress-integrator/0.juju-log Emitting Juju event secret_expired.
unit-nginx-ingress-integrator-0: 11:13:27 ERROR unit.nginx-ingress-integrator/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 557, in <module>
    main(NginxIngressCharm)
  File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/lib/charms/tls_certificates_interface/v3/tls_certificates.py", line 1971, in _on_secret_expired
    csr = event.secret.get_content()["csr"]
KeyError: 'csr'
unit-nginx-ingress-integrator-0: 11:13:27 ERROR juju.worker.uniter.operation hook "secret-expired" (via hook dispatching script: dispatch) failed: exit status 1
```

The `csr` key was introduced in a `tls_certifcates` library bump: https://github.com/canonical/nginx-ingress-integrator-operator/commit/170f3872ad46e4d111e8b0e64370cef99a005778 on revision 104.

This means that charms that have been deployed with a rev < 104 and later upgraded to >=104 are affected.

Workaround: Temporarily revert https://github.com/canonical/nginx-ingress-integrator-operator/commit/170f3872ad46e4d111e8b0e64370cef99a005778#diff-d09cfee654a477208d212323a440ed95ee448627762a42d8b631a1f855c2aedfR1980 (e.g. by ssh'ing into the unit) and run `juju resolve nginx-ingress-integrator/0`.

### To Reproduce

Deploy nginx-ingress-integrator with a revision < 104 and integrate it with a tls cert provider and ingress requirer. Afterwards, upgrade to revision 108 and let the secret expire (e.g. fire the event using jhack).

### Environment

juju 3.1.8, nginx-ingress-integrator revision 108

### Relevant log output

```shell
unit-nginx-ingress-integrator-0: 11:13:27 DEBUG unit.nginx-ingress-integrator/0.juju-log Emitting Juju event secret_expired.
unit-nginx-ingress-integrator-0: 11:13:27 ERROR unit.nginx-ingress-integrator/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 557, in <module>
    main(NginxIngressCharm)
  File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/venv/ops/main.py", line 544, in main
    manager.run()
  File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/venv/ops/main.py", line 520, in run
    self._emit()
  File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/venv/ops/main.py", line 509, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/venv/ops/framework.py", line 350, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/venv/ops/framework.py", line 849, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/venv/ops/framework.py", line 939, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-nginx-ingress-integrator-0/charm/lib/charms/tls_certificates_interface/v3/tls_certificates.py", line 1971, in _on_secret_expired
    csr = event.secret.get_content()["csr"]
KeyError: 'csr'
unit-nginx-ingress-integrator-0: 11:13:27 ERROR juju.worker.uniter.operation hook "secret-expired" (via hook dispatching script: dispatch) failed: exit status 1
unit-nginx-ingress-integrator-0: 11:13:27 INFO juju.worker.uniter awaiting error resolution for "secret-expired" hook
unit-nginx-ingress-integrator-0: 11:15:28 INFO juju.worker.uniter awaiting error resolution for "secret-expired" hook


secret (revelevant content changed)

foobar:
  revision: 1
  expires: 2024-08-11T10:38:05Z
  owner: nginx-ingress-integrator/0
  label: |-
    barfoo------BEGIN CERTIFICATE REQUEST-----
    foobar
    -----END CERTIFICATE REQUEST-----
  created: 2024-06-12T11:38:10Z
  updated: 2024-06-12T11:38:10Z
  content:
    certificate: |-
      -----BEGIN CERTIFICATE-----
     foobar
      -----END CERTIFICATE-----
```

**Comment by cbartz** [comment]
Seems to be fixed by https://github.com/canonical/tls-certificates-interface/pull/230/ and https://github.com/canonical/nginx-ingress-integrator-operator/pull/168

**Comment by cbartz** [comment]
Applying the latest rev 117 solved the problem mentioned here (though I ran into another one afterwards when juju tried to expire a non-existent secret), so I'll close this one.
