### ISSUE TITLE
Uncaught exception while removing ingress relation

### ISSUE THREAD

**Issue by claudiubelu** [canonical/nginx-ingress-integrator-operator#90]
### Bug Description

We're currently using the ``nginx-ingress-integrator`` charm (revision 79) for multiple charms. However, when we removed the ``ingress`` relation between it and another charm, the charm ended up in an error state (``hook failed: "ingress-relation-broken"``), with the stack trace seen below in ``juju debug-log``.

### To Reproduce

1. Deploy 2 charms with an ``ingress`` ``requires`` interface.
2. Deploy ``nginx-ingress-integrator`` charm (edge, rev 79).
3. Relate the 2 charms to ``nginx-ingress-integrator``.
4. Remove a relation.

### Environment

Juju version: 3.1.5
Environment: EKS

### Relevant log output

```shell
unit-ingress-0: 10:17:09 ERROR unit.ingress/0.juju-log ingress:58: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 1220, in <module>
    main(NginxIngressCharm)
  File "/var/lib/juju/agents/unit-ingress-0/charm/venv/ops/main.py", line 441, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-ingress-0/charm/venv/ops/main.py", line 149, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-ingress-0/charm/venv/ops/framework.py", line 344, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-ingress-0/charm/venv/ops/framework.py", line 841, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-ingress-0/charm/venv/ops/framework.py", line 930, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-ingress-0/charm/lib/charms/nginx_ingress_integrator/v0/ingress.py", line 395, in _on_relation_broken
    self.charm.on.ingress_broken.emit(event.relation)
  File "/var/lib/juju/agents/unit-ingress-0/charm/venv/ops/framework.py", line 344, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-ingress-0/charm/venv/ops/framework.py", line 841, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-ingress-0/charm/venv/ops/framework.py", line 930, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 1179, in _on_ingress_broken
    conf_or_rel = _ConfigOrRelation(self.model, {}, event.relation, self._multiple_relations)
  File "./src/charm.py", line 609, in _multiple_relations
    return len(self._deduped_relations()) > 1
  File "./src/charm.py", line 577, in _deduped_relations
    if self._gen_relation_dedup_key(relation) in nginx_route_relation_keys:
  File "./src/charm.py", line 547, in _gen_relation_dedup_key
    raise RuntimeError(f"can't retrieve remote application from relation {relation}")
RuntimeError: can't retrieve remote application from relation <ops.model.Relation ingress:58>
unit-ingress-0: 10:17:10 ERROR juju.worker.uniter.operation hook "ingress-relation-broken" (via hook dispatching script: dispatch) failed: exit status 1
```
```


### Additional context

_No response_

**Comment by weiiwang01** [comment]
Thank you for bringing this issue to our attention. The error suggests that Juju is unable to locate the remote application for the `ingress` relation (`id=58`). It hadn't occurred to me that a relation might still exist when a `relation-broken` event occurs. I'll confirm this behavior with the Juju team. 

Could you please offer more details regarding this error? Specifically, was the `ingress` relation `id=58` the relation removed? The relation id can be checked using the `juju show-unit` command.

**Comment by claudiubelu** [comment]
Unfortunately, I don't have that same scenario anymore, as I ran ``juju resolved --no-retry`` on the unit. Looking at its ``juju show-unit``, there's no relation ``id=58`` there:

```
ingress/0:
  workload-version: 25.3.0
  opened-ports: []
  charm: ch:amd64/focal/nginx-ingress-integrator-79
  leader: true
  life: alive
  relation-info:
  - relation-id: 51
    endpoint: ingress
    related-endpoint: ingress
    application-data:
      path-routes: /info
      rewrite-enabled: "False"
      service-hostname: myk8s.local
      service-name: app-info
      service-port: "6060"
    related-units:
      info/0:
        in-scope: true
        data:
          egress-subnets: 10.100.250.179/32
          ingress-address: 10.100.250.179
          private-address: 10.100.250.179
  - relation-id: 66
    endpoint: ingress
    related-endpoint: ingress
    application-data:
      path-routes: /api
      rewrite-enabled: "False"
      service-hostname: myk8s.local
      service-name: app-api
      service-port: "7070"
    related-units:
      api/0:
        in-scope: true
        data:
          egress-subnets: 10.100.134.110/32
          ingress-address: 10.100.134.110
          private-address: 10.100.134.110
  - relation-id: 67
    endpoint: ingress
    related-endpoint: ingress
    application-data:
      path-routes: /.well-known/acme-challenge
      rewrite-enabled: "False"
      service-hostname: myk8s.local
      service-name: certbot-k8s
      service-port: "80"
    related-units:
      certbot-k8s/0:
        in-scope: true
        data:
          egress-subnets: 10.100.168.45/32
          ingress-address: 10.100.168.45
          private-address: 10.100.168.45
  - relation-id: 68
    endpoint: ingress
    related-endpoint: ingress
    application-data:
      path-routes: /
      rewrite-enabled: "False"
      service-hostname: myk8s.local
      service-name: legend-studio
      service-port: "8080"
    related-units:
      frontend/0:
        in-scope: true
        data:
          egress-subnets: 10.100.123.225/32
          ingress-address: 10.100.123.225
          private-address: 10.100.123.225
  provider-id: ingress-0
  address: 192.168.3.207
```

I've tried replicating the scenario on a new model (+ nginx-ingress-controller rev 80 this time), and I didn't encounter this error. Perhaps that error occured because it happened before, and we ran ``juju resolved --no-retry`` then as well, and this issue occured again when removing one of its relations.

**Comment by weiiwang01** [comment]
This error likely occurs within a very short timeframe when the relation isn't entirely removed, yet the `relation-broken`  is emitted. I believe those relations can be safely ignored. If not, they will lead to errors in subsequent processes anyway.

I have created a pull request for this issue: https://github.com/canonical/nginx-ingress-integrator-operator/pull/92

For more information:

https://github.com/canonical/operator/blob/5c305b8d364800816083c3adb392e7c23313d2c6/ops/model.py#L1424-L1434
